on:
  workflow_dispatch:

name: Azure storageAccount ARM
inputs:
  resourceGroupName:
    description: "Provide the name of a resource group, only required for resource Group deployments."
    required: false
  subscriptionId:
    description: "Override the Subscription Id set by Azure Login."
    required: false 
  creds:
    description: "creds."
    required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: $INPUT_creds }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: $INPUT_subscriptionId
        resourceGroupName: $INPUT_resourceGroupName
        template: ./armtemplates/storageaccount.json
        parameters: 
          storageAccountType=Standard_LRS
          location=westeurope
        scope: resourcegroup
